### ISSUE TITLE
"Official" ROMs

### ISSUE THREAD

**Issue by mariomadproductions** [silverlays/NoIntro-Roms-Downloader#1]
I don't think this should say the ROMs are "official" (even in quotation marks), that doesn't really make sense. The particular romsets that this program use may be outdated or inadvertently corrupted. To check if the ROMs match the No-Intro database, the ROMs should be hashed and checked against the dat files from DAT-o-MATIC. There's currently no API for downloading from DAT-o-MATIC, but you could bundle the dats with the program and manually update them occasionally.

Edit: I may submit a pull request for this (and maybe some others improvements) at some point.

**Comment by silverlays** [comment]
Hello and thank you for your feedback. I allowed myself to specify "official" because the dumps come from the official NoIntro repos hosted on Archive.org (all those starting with <nointro.*>). It is however true that you score a point by talking about DAT-o-MATIC that could be integrated to check the quality of the dump after extraction. I'll see to integrate it for the next version. I also agree with you on adding a .dat updated regularly with each new version.

**Comment by silverlays** [comment]
I thought a little about your remark and made the decision to follow your recommendations. So I changed "official" to "date" in the <about> and the README.
